version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
#    groups:
#      rust-serde: # group updates of all serde crates togethers
#        patterns:
#          - "serde*"
#      rust: # group updates of all other crates togethers
#        patterns:
#          - "*"
