[package]
name = "roas"
version = "0.1.0"
edition = "2021"
authors = ["Sergey Vilgelm <sergey@vilgelm.com>"]
description = "Rust OpenAPI Specification"
readme = "README.md"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sv-tools/roas"
repository = "https://github.com/sv-tools/roas"
keywords = ["openapi", "swagger"]
categories = ["web-programming", "parser-implementations"]
include = ["src", "Cargo.toml", "README.md", "LICENSE-APACHE", "LICENSE-MIT", "dependencies-license.json"]

[dependencies]

[dev-dependencies]
cargo-license = { version = "0.5.1" }
