[package]
name = "roas"
version = "0.2.0"
edition = "2021"
authors = ["Sergey Vilgelm <sergey@vilgelm.com>"]
description = "Rust OpenAPI Specification"
readme = "README.md"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sv-tools/roas"
repository = "https://github.com/sv-tools/roas"
keywords = ["openapi", "swagger"]
categories = ["web-programming", "parser-implementations"]
include = ["src", "Cargo.toml", "README.md", "LICENSE-APACHE", "LICENSE-MIT", "dependencies-license.json"]

[package.metadata]
dependencies-license-file = "dependencies-license.json"

[features]
default = ["v2"]
v2 = []

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
serde_json = { version = "1.0.107" }
regex = { version = "1.10.2" }
enumset = { version = "1.1.3" }

[dev-dependencies]
cargo-license = { version = "0.5.1" }
