[package]
name = "roas"
version = "0.5.1"
edition = "2024"
authors = ["Sergey Vilgelm <sergey@vilgelm.com>"]
description = "Rust OpenAPI Specification"
readme = "README.md"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/sv-tools/roas"
repository = "https://github.com/sv-tools/roas"
keywords = ["openapi", "swagger"]
categories = ["web-programming", "parser-implementations"]
include = [
  "src",
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "dependencies-license.json",
]

[package.metadata]
dependencies-license-file = "dependencies-license.json"

[features]
default = ["v3_0"]
# Support for OpenAPI v2
v2 = []

# Support for OpenAPI v3.0.x
v3_0 = []

# Support for OpenAPI v3.1.x
# Feature is experimental and may change in the future
v3_1 = []

[dependencies]
enumset = "1.1.10"
monostate = "0.1.14"
regex = "1.11.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
