[alias]
install-tools = "install cargo-deny@0.14.17 cargo-license@0.6.1 cargo-llvm-cov@0.6.7 cargo-machete@0.6.1 cargo-nextest@0.9.67"
install-license = "install cargo-license@0.6.1"
update-tools = "install cargo-deny cargo-license cargo-llvm-cov cargo-machete cargo-nextest"
