use roas::validation::{IGNORE_UNUSED, Options};
use roas_codegen::{
    ConfigFile, DiagnosticKind, GenerateError, Input, Severity, SourceDocument, Target, generate,
    validate,
};
use std::path::Path;
use url::Url;

fn document(components: serde_json::Value) -> roas_codegen::ValidatedSourceDocument {
    let raw = serde_json::json!({
        "openapi": "3.2.0",
        "info": {"title": "t", "version": "1"},
        "paths": {},
        "components": {"schemas": components}
    });
    let bytes = serde_json::to_vec(&raw).unwrap();
    let doc = SourceDocument::parse(Input::Json(bytes), Url::parse("file:///t.json").unwrap())
        .expect("parses");
    validate(doc, IGNORE_UNUSED | Options::IgnoreMissingTags).expect("valid")
}

fn rust_config(toml: &str) -> roas_codegen::Config {
    ConfigFile::from_toml(toml, Path::new("/"))
        .unwrap()
        .merge(ConfigFile {
            target: Some(Target::Rust),
            ..Default::default()
        })
        .build()
        .unwrap()
}

fn pet() -> serde_json::Value {
    serde_json::json!({
        "Pet": {
            "type": "object",
            "description": "A pet.",
            "additionalProperties": false,
            "required": ["name"],
            "properties": {
                "name": {"type": "string", "minLength": 1},
                "tag": {"type": ["string", "null"]},
                "status": {"type": "string", "enum": ["available", "sold"]}
            }
        }
    })
}

#[test]
fn the_worked_example_generates_as_the_plan_shows() {
    let generation = generate(&document(pet()), &rust_config("")).expect("generates");
    assert_eq!(generation.files.len(), 1);
    let file = &generation.files[0];
    assert_eq!(file.path, Path::new("types.rs"));
    let code = &file.contents;
    let expected_fragments = [
        "// Code generated by roas. DO NOT EDIT.",
        "#[serde(deny_unknown_fields)]",
        "pub struct Pet {",
        "pub name: String,",
        "deserialize_with = \"double_option::deserialize\"",
        "pub tag: Option<Option<String>>,",
        "deserialize_with = \"reject_null::deserialize\"",
        "pub status: Option<PetStatus>,",
        "pub enum PetStatus {",
        "#[serde(rename = \"available\")]",
        "Available,",
        "Sold,",
        "mod double_option {",
        "mod reject_null {",
    ];
    for fragment in expected_fragments {
        assert!(code.contains(fragment), "missing {fragment:?} in:\n{code}");
    }
    assert!(
        !code.contains("Int64"),
        "no integer in this example:\n{code}"
    );
    assert!(
        generation.diagnostics.is_empty(),
        "{:?}",
        generation.diagnostics
    );
    let deps: Vec<&str> = generation
        .dependencies
        .rust
        .iter()
        .map(|d| d.name.as_str())
        .collect();
    assert_eq!(deps, ["serde", "serde_json"]);
}

#[test]
fn generation_is_byte_for_byte_deterministic() {
    let a = generate(&document(pet()), &rust_config("")).unwrap();
    let b = generate(&document(pet()), &rust_config("")).unwrap();
    assert_eq!(a.files, b.files);
}

#[test]
fn every_kind_renders_valid_rust() {
    let components = serde_json::json!({
        "Pet": {"type": "object", "required": ["petType"], "properties": {"petType": {"type": "string", "const": "Pet"}, "n": {"type": "integer", "format": "int32", "minimum": 0, "maximum": 10}}},
        "Cat": {"type": "object", "required": ["petType"], "properties": {"petType": {"type": "string", "enum": ["Cat"]}, "lives": {"type": "integer", "minimum": 0, "maximum": 9}}},
        "Animal": {"oneOf": [{"$ref": "#/components/schemas/Pet"}, {"$ref": "#/components/schemas/Cat"}], "discriminator": {"propertyName": "petType"}},
        "Loose": {"oneOf": [{"type": "string"}, {"type": "boolean"}]},
        "Either": {"anyOf": [{"$ref": "#/components/schemas/Pet"}, {"type": "string"}]},
        "Mixed": {"type": ["string", "number"]},
        "Composed": {"allOf": [{"$ref": "#/components/schemas/Pet"}, {"type": "object", "additionalProperties": false}]},
        "Merged": {"allOf": [{"type": "object", "properties": {"a": {"type": "string"}}}, {"type": "object", "properties": {"b": {"type": "boolean"}}}]},
        "Ids": {"type": "array", "items": {"type": "string", "format": "uuid"}},
        "Counts": {"type": "object", "additionalProperties": {"type": "number"}},
        "Alias": {"$ref": "#/components/schemas/Pet"},
        "Node": {"type": "object", "properties": {"next": {"$ref": "#/components/schemas/Node"}, "type": {"type": "string"}, "self": {"type": "boolean"}}},
        "Untyped": {"properties": {"x": {"type": "string"}}},
        "Anything": {},
        "Nothing": {"type": "null"}
    });
    let generation = generate(&document(components), &rust_config("")).expect("generates");
    let code = &generation.files[0].contents;
    for fragment in [
        "pub enum Animal {",
        "impl<'de> Deserialize<'de> for Animal {",
        "pub struct Loose {",
        "pub fn as_loose_variant_1(&self) -> Option<String>",
        "pub struct Either {",
        "pub struct Mixed {",
        "pub struct Composed {",
        "pub struct Merged {",
        "pub struct Ids(pub Vec<String>);",
        "pub struct Counts(pub std::collections::BTreeMap<String, f64>);",
        "pub type Alias = Pet;",
        "pub next: Option<Box<Node>>,",
        "pub r#type: Option<String>,",
        "pub self_: Option<bool>,",
        "pub struct Untyped {",
        "pub struct UntypedObject {",
        "pub struct Anything(pub serde_json::Value);",
        "pub struct Nothing(pub ());",
        "pub struct Int32(pub i32);",
        "pub struct Int64(pub i64);",
    ] {
        assert!(code.contains(fragment), "missing {fragment:?} in:\n{code}");
    }
    assert!(!generation.has_errors(), "{:?}", generation.diagnostics);
    let kinds: Vec<&DiagnosticKind> = generation.diagnostics.iter().map(|d| &d.kind).collect();
    assert!(
        kinds.iter().any(
            |k| matches!(k, DiagnosticKind::OpenComposition { keyword } if keyword == "oneOf")
        ),
        "{kinds:?}"
    );
    assert!(
        kinds.iter().any(
            |k| matches!(k, DiagnosticKind::OpenComposition { keyword } if keyword == "allOf")
        ),
        "{kinds:?}"
    );
    assert!(
        kinds
            .iter()
            .any(|k| matches!(k, DiagnosticKind::TypelessObject)),
        "{kinds:?}"
    );
}

#[test]
fn errors_suppress_types_but_generation_continues() {
    let components = serde_json::json!({
        "Bad": {"not": {"type": "string"}},
        "Holder": {"type": "object", "properties": {"bad": {"$ref": "#/components/schemas/Bad"}}},
        "Fine": {"type": "object", "properties": {"x": {"type": "boolean"}}},
        "External": {"$ref": "https://example.com/x.json#/X"}
    });
    let generation = generate(&document(components), &rust_config("")).expect("generates");
    let code = &generation.files[0].contents;
    assert!(code.contains("pub struct Fine {"), "{code}");
    assert!(!code.contains("pub struct Holder"), "{code}");
    assert!(!code.contains("Bad"), "{code}");
    assert!(!code.contains("External"), "{code}");
    assert!(generation.has_errors());
    let errors: Vec<&str> = generation
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .map(|d| d.pointer.as_str())
        .collect();
    assert_eq!(
        errors,
        [
            "/components/schemas/Bad",
            "/components/schemas/External/$ref"
        ],
        "{:?}",
        generation.diagnostics
    );
}

#[test]
fn configuration_reaches_the_output_and_is_checked() {
    let config = rust_config(
        "header = \"// SPDX-License-Identifier: MIT\"\nextra_imports = [\"use std::fmt;\"]\n[rust]\nderives = [\"Eq\"]\n[types.Pet]\nrename = \"Animal\"\nattrs = ['#[derive(Hash)]']\n[types.Pet.fields.tag]\nrename = \"label\"\nattrs = ['#[doc(hidden)]']\n",
    );
    let generation = generate(&document(pet()), &config).expect("generates");
    let code = &generation.files[0].contents;
    for fragment in [
        "// SPDX-License-Identifier: MIT",
        "use std::fmt;",
        "pub struct Animal {",
        "Hash)]",
        "#[serde(rename = \"tag\")]",
        "#[doc(hidden)]",
        "pub label: Option<Option<String>>,",
        "PartialEq, Eq, Serialize",
    ] {
        assert!(code.contains(fragment), "missing {fragment:?} in:\n{code}");
    }

    let error = generate(
        &document(pet()),
        &rust_config("[types.Dog]\nrename = \"X\"\n"),
    )
    .unwrap_err();
    assert!(
        matches!(&error, GenerateError::UnknownSelector { selector, candidates } if selector == "types.Dog" && candidates == &["Pet".to_owned()]),
        "{error}"
    );
    let error = generate(
        &document(pet()),
        &rust_config("[types.Pet.fields.color]\nrename = \"x\"\n"),
    )
    .unwrap_err();
    assert!(
        matches!(&error, GenerateError::UnknownSelector { selector, .. } if selector == "types.Pet.fields.color"),
        "{error}"
    );
    let error = generate(
        &document(pet()),
        &rust_config("[types.Pet.fields.tag]\nattrs = ['#[serde(default)]']\n"),
    )
    .unwrap_err();
    assert!(
        matches!(&error, GenerateError::ReservedAttribute { key, .. } if key == "default"),
        "{error}"
    );
}

#[test]
fn substitutions_are_spelled_and_listed() {
    let components = serde_json::json!({
        "Money": {"type": "object", "properties": {"amount": {"type": "string"}}},
        "Order": {"type": "object", "required": ["total", "when"], "properties": {"total": {"$ref": "#/components/schemas/Money"}, "when": {"type": "string", "format": "date-time"}}}
    });
    let config = rust_config(
        "[substitutions.Money.rust]\nname = \"my::Money\"\n[substitutions.date-time.rust]\nname = \"chrono::DateTime<chrono::Utc>\"\nimport = \"chrono\"\n",
    );
    let generation = generate(&document(components), &config).expect("generates");
    let code = &generation.files[0].contents;
    assert!(code.contains("pub total: my::Money,"), "{code}");
    assert!(
        code.contains("pub when: chrono::DateTime<chrono::Utc>,"),
        "{code}"
    );
    assert!(!code.contains("pub struct Money"), "{code}");
    let deps: Vec<&str> = generation
        .dependencies
        .rust
        .iter()
        .map(|d| d.name.as_str())
        .collect();
    assert_eq!(deps, ["chrono", "serde", "serde_json"]);
    let holder = serde_json::json!({
        "Money": {"type": "string"},
        "Order": {"type": "object", "properties": {"total": {"$ref": "#/components/schemas/Money"}}}
    });
    let error = generate(
        &document(holder),
        &rust_config("[substitutions.Money.go]\nname = \"x\"\n"),
    )
    .unwrap_err();
    assert!(matches!(error, GenerateError::Config(_)), "{error}");
}

#[test]
fn codegen_extensions_are_gated() {
    let components = serde_json::json!({
        "Pet": {"type": "object", "x-rust-attrs": "#[derive(Hash, Eq)]", "properties": {"name": {"type": "string", "x-rust-attrs": ["#[doc(hidden)]"]}}}
    });
    let off = generate(&document(components.clone()), &rust_config("")).unwrap();
    assert!(!off.files[0].contents.contains("Hash"));
    assert_eq!(
        off.diagnostics
            .iter()
            .filter(|d| matches!(d.kind, DiagnosticKind::IgnoredExtension { .. }))
            .count(),
        2,
        "{:?}",
        off.diagnostics
    );
    let on = generate(
        &document(components),
        &rust_config("allow_codegen_extensions = true\n"),
    )
    .unwrap();
    assert!(
        on.files[0].contents.contains("Hash, Eq)]"),
        "{}",
        on.files[0].contents
    );
    assert!(on.files[0].contents.contains("#[doc(hidden)]"));
}

#[test]
fn unsupported_configuration_is_refused_up_front() {
    let error = generate(
        &document(pet()),
        &rust_config("layout = \"file_per_type\"\n"),
    )
    .unwrap_err();
    assert!(matches!(error, GenerateError::Unsupported(_)), "{error}");
    let go = ConfigFile {
        target: Some(Target::Go),
        ..Default::default()
    }
    .build()
    .unwrap();
    let error = generate(&document(pet()), &go).unwrap_err();
    assert!(matches!(error, GenerateError::Unsupported(_)), "{error}");
    let error = generate(&document(pet()), &rust_config("exact_numbers = true\n")).unwrap_err();
    assert!(
        matches!(
            error,
            GenerateError::Config(_) | GenerateError::Fidelity(_) | GenerateError::Unsupported(_)
        ),
        "{error}"
    );
}

#[test]
fn an_unknown_root_dialect_generates_nothing() {
    let raw = serde_json::json!({
        "openapi": "3.2.0",
        "info": {"title": "t", "version": "1"},
        "jsonSchemaDialect": "https://example.com/my-dialect",
        "paths": {},
        "components": {"schemas": {"Pet": {"type": "object"}}}
    });
    let doc = SourceDocument::parse(
        Input::Json(serde_json::to_vec(&raw).unwrap()),
        Url::parse("file:///t.json").unwrap(),
    )
    .unwrap();
    let doc = validate(doc, IGNORE_UNUSED | Options::IgnoreMissingTags).unwrap();
    let generation = generate(&doc, &rust_config("")).unwrap();
    assert!(generation.files.is_empty());
    assert!(matches!(
        generation.diagnostics[0].kind,
        DiagnosticKind::UnsupportedDialect { .. }
    ));
}

/// Dump the worked example for a look, when asked.
#[test]
fn dump_worked_example_when_requested() {
    let Ok(path) = std::env::var("ROAS_CODEGEN_DUMP") else {
        return;
    };
    let generation = generate(&document(pet()), &rust_config("")).unwrap();
    std::fs::write(path, &generation.files[0].contents).unwrap();
}
