name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
    outputs:
      publish:
        value: ${{ jobs.RustMeta.outputs.publish }}
  schedule:
    - cron: "0 0 * * 0"

env:
  CARGO_TERM_COLOR: always

permissions: read-all

jobs:
  RustMeta:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.rustmeta.outputs.matrix }}
      publish: ${{ steps.rustmeta.outputs.publish }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
      - uses: sv-tools/rust-metadata-action@8618602bef8488998677a4ed006f9a9a35cf6756 # v0.1.0
        id: rustmeta
  Format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
      - run: cargo fmt --all --check --verbose
  Clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          cache-targets: false
          cache-all-crates: true
      - run: cargo tools
      - run: cargo clippy --all-features --verbose -- --deny warnings
      - run: cargo clippy --all-features --quiet --message-format=json | cargo-action-fmt
        if: failure()
  TestsJob:
    needs: RustMeta
    strategy:
      matrix:
        args: ${{ fromJSON(needs.RustMeta.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          cache-targets: false
          cache-all-crates: true
      - run: cargo tools
      - name: Run tests
        run: cargo llvm-cov nextest ${{ matrix.args }} --no-default-features --no-fail-fast --verbose
      - name: Prepare coverage report
        if: ${{ !cancelled() }}
        run: cargo llvm-cov report --lcov --output-path coverage.lcov
      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  Tests:
    needs: TestsJob
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        if: ${{ needs.TestsJob.result != 'success' }}
        run: exit 1
  Deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          cache-targets: false
          cache-all-crates: true
      - run: cargo tools
      - name: Machete
        run: cargo machete
      - name: Deny
        run: cargo deny check all
  PublishJob:
    needs: RustMeta
    strategy:
      matrix:
        package: ${{ fromJSON(needs.RustMeta.outputs.publish) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          cache-targets: false
          cache-all-crates: true
      - run: cargo tools
      - run: cargo license --all-features --avoid-dev-deps --json > dependencies-license.json
      - name: Dry run publish
        run: cargo publish --package ${{ matrix.package }} --all-features --allow-dirty --dry-run --verbose
      - name: Packaging
        run: cargo package --package ${{ matrix.package }} --all-features --list --allow-dirty
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.package }}-crate
          path: target/package/${{ matrix.package }}-*.crate
  Publish:
    needs: PublishJob
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        if: ${{ needs.PublishJob.result != 'success' }}
        run: exit 1
