name: Publish

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/checks.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.5.0
      - run: cargo install cargo-license
      - run: cargo license --all-features --avoid-dev-deps --json > dependencies-license.json
      - uses: rust-lang/crates-io-auth-action@e919bc7605cde86df457cf5b93c5e103838bd879 # v1.0.1
        id: auth
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish --all-features --allow-dirty --verbose
