name: Publish

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: read-all

jobs:
  Build:
    uses: ./.github/workflows/checks.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  Publish:
    needs:
      - Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.Build.outputs.publish) }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.5.0
      - run: cargo install cargo-license
      - run: cargo license --all-features --avoid-dev-deps --json > dependencies-license.json
      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec # v1.0.3
        id: auth
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish --package ${{ matrix.package }} --all-features --allow-dirty --verbose
