name: Publish

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/checks.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-license
      - name: Publish
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo license --all-features --avoid-dev-deps --json > dependencies-license.json
          cargo publish --all-features --allow-dirty --verbose
