name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --all-features --verbose
      - name: Format
        run: cargo fmt --all --check --verbose
      - name: Clippy
        run: cargo clippy
      - name: Install tools
        run: cargo install cargo-nextest cargo-machete cargo-license cargo-deny cargo-llvm-cov
      - name: Run tests
        continue-on-error: true
        run: |
          cargo llvm-cov nextest --all-features --all-targets --no-fail-fast
          cargo llvm-cov report --lcov --output-path coverage.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage/*.lcov
      - name: Machete
        run: cargo machete
      - name: Deny
        run: cargo deny check all
      - name: Dry run publish
        run: |
          cargo license --all-features --avoid-dev-deps --json > dependencies-license.json
          cargo publish --all-features --allow-dirty --dry-run
          cargo package --all-features --list --allow-dirty
